/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author herned1
 */
public class AgregarDatos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarDatos
     */
    public AgregarDatos() {
        initComponents();
        Conexion.conexion();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        this.setTitle("Agregar nuevos usuarios y material");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(450, 300);
        buttonIcon();
        buttonIcon2();
        buttonIcon3();
        this.getContentPane().setBackground(Color.lightGray);

    }

    String directory = System.getProperty("user.dir");

    private void buttonIcon() {
        String imageRoute;
        imageRoute = directory + "\\imagenes\\" + "back.png";
        ImageIcon imagen = new ImageIcon(imageRoute);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(labelButton.getWidth(), labelButton.getHeight(), Image.SCALE_DEFAULT));
        labelButton.setIcon(icono);
        this.repaint();
    }
    
    private void buttonIcon2() {
        String imageRoute;
        imageRoute = directory + "\\imagenes\\" + "add.png";
        ImageIcon imagen = new ImageIcon(imageRoute);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(labelButtonAdd.getWidth(), labelButtonAdd.getHeight(), Image.SCALE_DEFAULT));
        labelButtonAdd.setIcon(icono);
        this.repaint();
    }
    private void buttonIcon3() {
        String imageRoute;
        imageRoute = directory + "\\imagenes\\" + "add.png";
        ImageIcon imagen = new ImageIcon(imageRoute);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(labbelButtonAdd2.getWidth(), labbelButtonAdd2.getHeight(), Image.SCALE_DEFAULT));
        labbelButtonAdd2.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAgregarUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelButton = new javax.swing.JLabel();
        labelButtonAdd = new javax.swing.JLabel();
        labbelButtonAdd2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Agregar nuevo usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Agregar nuevo material");

        labelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonMouseClicked(evt);
            }
        });

        labelButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonAddMouseClicked(evt);
            }
        });

        labbelButtonAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labbelButtonAdd2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labbelButtonAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAgregarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAgregarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labbelButtonAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(labelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonMouseClicked
        Principal p = new Principal();
        p.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_labelButtonMouseClicked

    private void labelButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonAddMouseClicked
        String usuarioNuevo = txtAgregarUser.getText();
        try {
            Conexion.nuevoNombre(usuarioNuevo);
            JOptionPane.showMessageDialog(null, "El usuario fue agregado con exito");
            txtAgregarUser.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }
    }//GEN-LAST:event_labelButtonAddMouseClicked

    private void labbelButtonAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labbelButtonAdd2MouseClicked
        
        String materialNuevo = txtMat.getText();
        Conexion nc = new Conexion();
        try {
            nc.nuevoMaterial(materialNuevo);
            JOptionPane.showMessageDialog(null, "El material fue agregado con exito");
            txtMat.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }
    }//GEN-LAST:event_labbelButtonAdd2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labbelButtonAdd2;
    private javax.swing.JLabel labelButton;
    private javax.swing.JLabel labelButtonAdd;
    private javax.swing.JTextField txtAgregarUser;
    private javax.swing.JTextField txtMat;
    // End of variables declaration//GEN-END:variables
}
