/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author herned1
 */
public class RegistroFinal extends javax.swing.JFrame {

    public static DefaultTableModel modeloTabla;
    private Dimension dim;

    public RegistroFinal() {
        modeloTabla = new DefaultTableModel(null, getColumnas());
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        this.setTitle("Tabla de entregas");
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
//this.setLocation(300, 150);
//        this.setSize(1350, 800);
        tableDatos.setRowHeight(35);
        Conexion.conexion();
        setfilas();
        buttonIcon();
        this.getContentPane().setBackground(Color.lightGray);
    }

    private String[] getColumnas() {

        String columna[] = new String[]{"Nombre", "Material", "Fecha de prestamo", "Fecha de entrega"};

        return columna;
    }

    private void setfilas() {

        Connection con = Conexion.con;
        String sql = "select nombre,material,fecha,fechafinal from reportefinal";
        try {
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet res = st.executeQuery();
            Object datos[] = new Object[4];

            while (res.next()) {
                for (int i = 0; i < 4; i++) {
                    datos[i] = res.getObject(i + 1);
                }
                modeloTabla.addRow(datos);
            }
            res.close();
        } catch (Exception e) {
        }
    }
    String directory = System.getProperty("user.dir");

    private void buttonIcon() {
        String imageRoute;
        imageRoute = directory + "\\imagenes\\" + "back.png";
        ImageIcon imagen = new ImageIcon(imageRoute);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(labelReturn.getWidth(), labelReturn.getHeight(), Image.SCALE_DEFAULT));
        labelReturn.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();
        labelReturn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDatos.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        tableDatos.setModel(modeloTabla);
        jScrollPane1.setViewportView(tableDatos);

        labelReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReturnMouseClicked
        Principal p = new Principal();
        p.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_labelReturnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReturn;
    private javax.swing.JTable tableDatos;
    // End of variables declaration//GEN-END:variables

}
